# Default values for arch-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

nameOverride: arch-health
fullnameOverride: arch-health
containerPort: 8000

imageConfig:
  pullPolicy: IfNotPresent

image:
  repository: phichersandbox/arch-health

service:
  type: NodePort
  port: 8084

metrics:
  serviceMonitor:
    enabled: true

ingress:
  enabled: true
  hosts:
    - host: arch.homework
      paths: ["/"]

postgresql:
  enabled: true
  postgresqlUsername: myuser
  postgresqlPassword: passwd
  postgresqlDatabase: myapp
  postgresqlHost: arch-chart-postgresql
  postgresqlPort: 80
  persistence:
    subPath: postgres
  service:
    type: NodePort
    port: "5432"
