{
 "title": "Arch Health",
 "time": { "from": "2020-09-09T17:10:29.983Z", "to": "2020-09-09T17:10:59.594Z" },
 "templating": {
  "list": [
   {
    "name": "pod",
    "query": "kube_pod_container_info{namespace=\"$namespace\"}"
   },
   { "name": "container", "query": "arch-chart" },
   { "name": "namespace", "query": "label_values(namespace)" },
   {
    "name": "timeWindow",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Nginx", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 23, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket [$timeWindow])) by (le))",
     "legendFormat": "0.5"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket [$timeWindow])) by (le))",
     "legendFormat": "0.95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket [$timeWindow])) by (le))",
     "legendFormat": "0.99"
    }
   ]
  },
  {
   "title": "RPM",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(increase(nginx_ingress_controller_request_duration_seconds_count{namespace=\"$namespace\"}[$timeWindow]))",
     "legendFormat": "Rate"
    }
   ]
  },
  {
   "title": "Error rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(nginx_ingress_controller_request_duration_seconds_count{namespace=\"$namespace\", status=~\"5.*\"}[$timeWindow])",
     "legendFormat": "{{status}}"
    }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_user_seconds_total{namespace=\"$namespace\",pod=\"$pod\",container=\"$container\"}[10m]))",
     "legendFormat": "user"
    },
    {
     "expr": "sum(rate(container_cpu_system_seconds_total{namespace=\"$namespace\",pod=\"$pod\",container=\"$container\"}[10m]))",
     "legendFormat": "system"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(container_memory_usage_bytes{namespace=\"$namespace\",pod=\"$pod\",container=\"$container\"}) by (namespace, pod, container)",
     "legendFormat": "memory"
    }
   ]
  },
  { "title": "Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(ktor_http_server_requests_seconds_bucket [1m])) by (le))",
     "legendFormat": "0.5"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(ktor_http_server_requests_seconds_bucket [1m])) by (le))",
     "legendFormat": "0.95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(ktor_http_server_requests_seconds_bucket [1m])) by (le))",
     "legendFormat": "0.99"
    },
    {
     "expr": "max(max_over_time(ktor_http_server_requests_seconds_max{route=~\"/prometheus.*\"} [1m]))",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "RPM",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(increase(ktor_http_server_requests_seconds_count[1m]))",
     "legendFormat": "RPM"
    }
   ]
  },
  {
   "title": "Error rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(ktor_http_server_requests_seconds_count{status=~\"5.*\"}[1m])) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  }
 ]
}